config/routes.rb
TenderScraper::Application.routes.draw do
  resources :tenders do
    member do
      get 'unlock'
      get 'lock'
    end
    collection do
      get 'get_statuses'
    end
  end
  root :to => 'tenders#index'
end

app/models/tender.rb
class Tender < ActiveRecord::Base
  serialize :cpv_codes, Array
  after_initialize :set_defaults
  before_save :format_attributes
  validates_uniqueness_of :url
  scope :created_since, lambda { |ago|
    date = ( ( ago ? Date.parse(ago) : Date.today ).to_time - 2.hours ).to_date # correction according to UTC
    where("tenders.created_at >= ?",  date)
  }

  self.per_page = 10
  STATUSES      = [ :new, :edited, :marked_for_export, :exported ]
  LOCK_INTERVAL = 5*60 #5 min
  
  MESSAGES = 
  {
    :locked           => 'You need to lock this tender for editing before edit it!',
    :locked_by_others => 'This tender is already locked for editing by another user!',
    :locked_for_user  => 'Tender successfully locked for editing! You may now update tender fields!',
    :saved            => 'Tender successfully saved!',
    :general_error    => 'System error, please, try again!',
    :could_not_save   => 'Your lock has been expired while you were editing tender! Lock this tender again before editing and saving!',
    :lock_released    => 'Lock successfully realeased!'
  }
  
  TENDER_FIELD_ORDER = [ 
    ["general", 
      [
        "case_number",
        "heading",
        "cpv_codes",
        "nuts_code"
      ]
    ],
    ["dates", 
      [
        [ "material_closing_date", "material_closing_time" ],
        [ "closing_date", "closing_time" ],
        [ "opening_date", "opening_time" ]
      ]
    ],
    ["buyer-contact",  
      [
        [ "registration_number", "contact" ],
        [ "buyer_name", "phone_number" ],
        [ "address", "mobile_phone_number" ],
        [ "city", "fax_number"],
        [ "post_code", "email"],
        [ "country", "website"]
      ]
    ]
  ]
  
  NONE_EXPORTABLE_FIELDS = 
    [
     "id",
     "exported_times",
     "exported_at",
     "last_time_exported_by",
     "created_at",
     "updated_at",
     "last_time_edited_by",
     "marked_for_export",
     "lock_status",
     "locked_by",
     "locked_at",
     "status"
    ]
  
  NONE_EDITABLE_FIELDS = NONE_EXPORTABLE_FIELDS + 
    [
     "document",
     "url"
     ]
  
  #class methods
  class << self
    def editable_fields
      column_names - NONE_EDITABLE_FIELDS
    end
    
    def misc_fields
      editable_fields - TENDER_FIELD_ORDER.flatten
    end
    
    def exportable_fields
      column_names - NONE_EXPORTABLE_FIELDS
    end
    
    def search(params = {}, without_pagination=false)
      params = {"page" => 1}.merge(params)

      unless without_pagination
        created_since(params[:created_at]).where( clean_params(params) ).page(params["page"]).order('created_at DESC, id DESC')
      else
        created_since(params[:created_at]).where( clean_params(params) ).order('created_at DESC')
      end
    end
    
    def clean_params(params)
      params.reject {|key,value| !column_names.include?(key.to_s) || key == "created_at" }
    end
    
    def get_statuses(params)
      where('id in (:ids)', :ids => params.map { |k,v| k.to_i }).inject({}) do |memo, tender|
        memo[tender.id.to_s] = tender.status.capitalize unless tender.status == params[tender.id.to_s]
        memo
      end
    end
  end
  
  #form disabled a) if it's locked for everyone (no one has intended to edit this tender)
  #b) if it's locked by another user for editing
  def locked?(session_id)
    lock_status == 'locked' || ( lock_status == 'locked_for_editing' && locked_by != session_id.to_s )
  end
  
  def lock_expired?
    locked_at + LOCK_INTERVAL < Time.now
  end
  
  # available if status not locked
  # and ( if status is locked_for_editing, then lock must been made by current_user
  # or if locked for editing by another user and lock has expired
  def available_for_edit?(session_id)
    !locked?(session_id) || ( lock_status = 'locked_for_editing' && lock_expired? )
  end
  
  # tender can be unlocked for editing if it's generally locked (for everyone)
  # or user lock has been expired
  def available_for_unlock?
    lock_status == 'locked' || lock_expired?
  end
  
  def update_tender(params, session_id)
    default_params = { :lock_status => 'locked', :status => :edited }
    
    unless available_for_edit?(session_id)
      errors[:errors] << MESSAGES[:locked_by_others]
      return false
    end

    unless update_attributes(params.reject{|k,v| !Tender.editable_fields.include?(k.to_s)}.merge(default_params))
      errors[:errors] << MESSAGES[:general_error] if errors.empty?
      return false
    end
    true
  end
  
  def lock(session_id)
    if session_id.to_s == locked_by
      self.lock_status = 'locked'
    else
      return {:msg => MESSAGES[:locked_by_others], :status => 'error'}
    end
    
    return {:msg => MESSAGES[:lock_released], :status => 'info'} if self.save
    {:msg => MESSAGES[:general_error], :status => 'error'}
  end
  
  def unlock(session_id)
    result = {:status => 'error'}
    
    if available_for_unlock?
      if update_attributes(:lock_status => 'locked_for_editing', :locked_at => Time.now, :locked_by => session_id)
        result[:msg]    = MESSAGES[:locked_for_user]
        result[:status] = 'info'
        return result
      else
        result[:msg] = MESSAGES[:general_error]
      end
    else
      result[:msg]   = MESSAGES[:locked_by_others]
    end
    
    result
  end
  
  def to_xml
    Tender.exportable_fields.inject({}) do |memo, k| 
      if (k == "cpv_codes")
        memo[:cpv_codes] = (self.send k)
      else
        memo[k] = (self.send k).to_s
      end
      
      memo 
    end.to_xml(:skip_instruct => true, :skip_types => true)
  end
  
  def marked?
    status == :marked_for_export
  end
  
  private
  def set_defaults
    if self.id.nil?
      self.status         = :new
      self.exported_times = 0
      self.lock_status    = 'locked'
    end
  end
  
  def format_attributes
    self.cpv_codes = cpv_codes.split(/\s*,\s*/) unless cpv_codes.is_a?(Array)
  end
  
end

app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  before_filter :find_tender, :only => [ :update, :lock, :unlock ]
  
  def index
    #FIXME:looks ugly
    @tenders = request.accept.match(/xml/) ? Tender.search(params, false) : Tender.search(params)
    
    respond_to do |format|
      format.html { render :partial => "tender_list" if params["ajax"] }
      format.xml  { render :xml => TenderXmlBuilder.xml(@tenders) }
    end
  end
  
  def update
    flash[:notice] = Tender::MESSAGES[:saved] if @tender.update_tender(params[:tender], @session_id)
    render :partial => 'tender', :locals => { :tender => @tender }
  end
  
  def lock
    respond_to do |format|
      format.json { render :json => @tender.lock(@session_id) }
    end
  end
  
  def unlock
    respond_to do |format|
      format.json { render :json => @tender.unlock(@session_id) }
    end
  end
  
  def get_statuses
    sleep(5)
    respond_to do |format|
      format.json { render :json => Tender.get_statuses(params[:tender_statuses]) }
    end
  end
  
  private
  def find_tender
    @tender = Tender.find(params[:id])
  end
end

app/helpers/tenders_helper.rb
module TendersHelper
  def tender_field_label(attrib)
    attrib = attrib.humanize
    attrib.match(/phone|fax/i) ? attrib.sub(/number/,'').strip : attrib
  end
  
  def tender_field_value(f, attrib)
    (attrib == 'cpv_codes' ? f.object.send(attrib).join(' , ') : f.object.send(attrib) ).to_s
  end
  
  def tender_field_helper(f, attrib, options={})
    options = { :disabled => true, :label => tender_field_label(attrib), :value => tender_field_value(f, attrib) }.merge(options)
    options[:class] = options[:class].to_s + '.span5'
    
    field = if attrib.match /email/
      "email_field"
    else
      "text_field"
    end
    
    f.send field, attrib.to_sym, options[:label], options
  end
  
  def tender_label(tender)
    label_type = case tender.status.to_sym
      when :new
        "success"
      when :edited, :marked_for_export
        "warning"
      when :exported
        "important"
      end
      
    "<span id='status-label-#{tender.id}' class='label #{label_type}'>#{tender.status.to_s.capitalize}</span>".html_safe
  end
  
  def buyer_contact_legend
    "<span class='buyer-legend'>Buyer</span><span class='contact-legend'>Contact</span>".html_safe
  end
end

app/views/tenders/_tender.html.haml
.tender-controls
  .label-container
    .label-load-indicator-container
      = image_tag 'load-indicator-small.gif', :id => "label-load-indicator-#{tender.id}", :class => "label-load-indicator"
    = tender_label tender
  - if tender.available_for_unlock?
    = button_tag 'Edit', :class => 'btn form-unlocker', :id => "unlock-tender-form-#{tender.id}", :"data-url" => unlock_tender_path(tender.id)
  - else
    = button_tag 'Edit', :class => 'btn form-unlocker', :id => "unlock-tender-form-#{tender.id}", :"data-url" => unlock_tender_path(tender.id), :disabled => true
  .marker-container{ :id => "marker-container-#{tender.id}"}
    = label_tag 'Mark for export'
    = check_box_tag "marker-cb-#{tender.id}", "1", tender.marked?, :class => 'marker-cb'
  = render :partial => 'layouts/msg_box', :locals => {:subject => tender}
= link_to tender.url, tender.url
= twitter_bootstrap_form_for tender, :remote => true do |f|
  = f.inputs do
    - Tender::TENDER_FIELD_ORDER.each do |cat|
      - if cat[0] == 'dates'
        = f.inputs '', :class => 'hidden_legend date_inputs_container' do
          - cat[1].each do |attr|
            .inline-inputs
              = tender_field_helper f, attr[0], {:disabled => tender.locked?(@session_id) }
              = tender_field_helper f, attr[1], {:disabled => tender.locked?(@session_id), :label => ', time', :class => '' }
      - elsif cat[0] == 'buyer-contact'
        = f.inputs buyer_contact_legend, :class => 'buyer_inputs_container' do
          - cat[1].each do |attr|
            .inline-inputs
              = tender_field_helper f, attr[0], {:disabled => tender.locked?(@session_id) }
              = tender_field_helper f, attr[1], {:disabled => tender.locked?(@session_id), :class => '' }
      - else
        = f.inputs "#{cat[0].capitalize unless cat[0] == 'general'}", :class => "#{cat[0] == 'general' ? 'hidden_legend' : 'form_legend'}" do
          - cat[1].each do |attr|
            = tender_field_helper f, attr, {:disabled => tender.locked?(@session_id) }
    = f.inputs "Misc", :class => 'form_legend' do
      - Tender.misc_fields.each do |attr|
        = tender_field_helper f, attr, { :disabled => tender.locked?(@session_id) }
  = f.actions do
    - if tender.locked?(@session_id)
      = f.submit 'Save', :disabled => "true", :id => "tender-#{tender.id}-submit-btn"
      = button_tag  'Cancel', :type => 'reset', :"data-url" => lock_tender_path(tender), :class => 'btn cancel', :id => "tender-#{tender.id}-cancel-btn", :disabled => "true"
    - else
      = f.submit 'Save', :id => "tender-#{tender.id}-submit-btn"
      = button_tag  'Cancel', :type => 'reset', :"data-url" => lock_tender_path(tender), :class => 'btn cancel', :id => "tender-#{tender.id}-cancel-btn"

app/views/tenders/_tender_list.html.haml
- unless @tenders.empty?
  - @tenders.each do |t|
    %div{:class => ".span16 load-indicator", :id => "load-indicator-container-#{t.id}"}
      = image_tag "load_indicator.gif"
    .tender-wrapper{:id => "tender-wrapper-#{t.id}"}
      = render :partial => "tender", :locals => {:tender => t}
- else
  %div{:class => "alert-message warning", :id => 'tenders-scraped-msg' }
    %p No new tenders!

app/views/tenders/index.html.haml
#tender-container{"data-url" => tenders_url, "data-status-url" => get_statuses_tenders_url }
  = render "tender_list"
#load-indicator-container{:class => ".span16 load-indicator"}
  = image_tag "load_indicator.gif"